name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: set up node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm install -g pnpm && pnpm install --no-frozen-lockfile

      - name: Run tests
        run: pnpm test

      - name: Run lint
        run: pnpm run lint
